[changelog]
header = """
# Changelog (Rust)\n
All notable changes to the Rust crates will be documented in this file.\n
"""
body = """
{%- macro remote_url() -%}
  https://github.com/medmodels/graphrecords
{%- endmacro -%}

{% if version -%}
  ## [{{ version | trim_start_matches(pat="rust-") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{% else -%}
  ## [Unreleased]
{% endif -%}

{% for group, commits in commits | group_by(attribute="group") %}
  ### {{ group | striptags | trim | upper_first }}
  {% for commit in commits %}
    - {{ commit.message | upper_first | trim }}\
      {% if commit.breaking %} (**breaking**){% endif %}\
  {% endfor %}
{% endfor %}\n
"""
footer = ""
trim = true

[git]
conventional_commits = true
filter_unconventional = true
split_commits = false
tag_pattern = "rust-.*"
sort_commits = "newest"

commit_parsers = [
  { message = "^release", skip = true },
  { message = "^ci", skip = true },
  { message = "^chore", skip = true },
  { message = "^[a-z]+\\(python\\)", skip = true },
  { message = "^feat", group = "Features" },
  { message = "^fix", group = "Bug Fixes" },
  { message = "^refactor", group = "Refactoring" },
  { message = "^docs", group = "Documentation" },
  { message = "^test", group = "Testing" },
  { message = "^build", group = "Build" },
]
