[package]
name = "graphrecords"
version = { workspace = true }
description = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }
license = { workspace = true }
readme = "../../README.md"

[dependencies]
graphrecords-core = { workspace = true }
graphrecords-utils = { workspace = true }
graphrecords-query = { workspace = true }
graphrecords-overview = { workspace = true }

[features]
serde = ["graphrecords-core/serde"]
io = ["graphrecords-core/io"]
plugins = ["graphrecords-core/plugins"]
polars = ["graphrecords-core/polars"]
arrow = ["graphrecords-core/arrow"]
dynamic = ["graphrecords-query/dynamic"]

[lints]
workspace = true
