from typing import Callable, Dict, List, Optional, Sequence

from graphrecords._graphrecords.overview import PyGroupOverview, PyOverview
from graphrecords._graphrecords.querying import PyEdgeOperand, PyNodeOperand
from graphrecords._graphrecords.schema import PySchema
from graphrecords.querying import PyQueryReturnOperand, QueryResult
from graphrecords.types import (
    Attributes,
    AttributesInput,
    EdgeIndex,
    EdgeIndexInputList,
    EdgeTuple,
    GraphRecordAttribute,
    GraphRecordValue,
    Group,
    GroupInputList,
    NodeIndex,
    NodeIndexInputList,
    NodeTuple,
    PluginName,
    PolarsDataFramesExport,
    PolarsEdgeDataFrameInput,
    PolarsNodeDataFrameInput,
    PyPlugin,
)

class PyGraphRecord:
    nodes: List[NodeIndex]
    edges: List[EdgeIndex]
    groups: List[Group]
    plugins: List[PluginName]

    def __init__(self) -> None: ...
    def _to_bytes(self) -> bytes: ...
    @staticmethod
    def _from_bytes(data: bytes) -> PyGraphRecord: ...
    @staticmethod
    def with_schema(schema: PySchema) -> PyGraphRecord: ...
    @staticmethod
    def with_plugins(plugins: Dict[PluginName, PyPlugin]) -> PyGraphRecord: ...
    @staticmethod
    def from_tuples(
        nodes: Sequence[NodeTuple],
        edges: Optional[Sequence[EdgeTuple]] = None,
        schema: Optional[PySchema] = None,
    ) -> PyGraphRecord: ...
    @staticmethod
    def from_dataframes(
        nodes_dataframes: List[PolarsNodeDataFrameInput],
        edges_dataframes: List[PolarsEdgeDataFrameInput],
        schema: Optional[PySchema] = None,
    ) -> PyGraphRecord: ...
    @staticmethod
    def from_nodes_dataframes(
        nodes_dataframes: List[PolarsNodeDataFrameInput],
        schema: Optional[PySchema] = None,
    ) -> PyGraphRecord: ...
    @staticmethod
    def from_ron(path: str) -> PyGraphRecord: ...
    def to_ron(self, path: str) -> None: ...
    def to_dataframes(self) -> PolarsDataFramesExport: ...
    def add_plugin(self, name: PluginName, plugin: PyPlugin) -> None: ...
    def remove_plugin(self, name: PluginName) -> None: ...
    def get_schema(self) -> PySchema: ...
    def set_schema(
        self, schema: PySchema, bypass_plugins: bool = False
    ) -> None: ...
    def freeze_schema(self, bypass_plugins: bool = False) -> None: ...
    def unfreeze_schema(self, bypass_plugins: bool = False) -> None: ...
    def node(self, node_index: NodeIndexInputList) -> Dict[NodeIndex, Attributes]: ...
    def edge(self, edge_index: EdgeIndexInputList) -> Dict[EdgeIndex, Attributes]: ...
    def outgoing_edges(
        self, node_index: NodeIndexInputList
    ) -> Dict[NodeIndex, List[EdgeIndex]]: ...
    def incoming_edges(
        self, node_index: NodeIndexInputList
    ) -> Dict[NodeIndex, List[EdgeIndex]]: ...
    def edge_endpoints(
        self, edge_index: EdgeIndexInputList
    ) -> Dict[EdgeIndex, tuple[NodeIndex, NodeIndex]]: ...
    def edges_connecting(
        self,
        source_node_indices: NodeIndexInputList,
        target_node_indices: NodeIndexInputList,
    ) -> List[EdgeIndex]: ...
    def edges_connecting_undirected(
        self,
        source_node_indices: NodeIndexInputList,
        target_node_indices: NodeIndexInputList,
    ) -> List[EdgeIndex]: ...
    def remove_nodes(
        self, node_index: NodeIndexInputList, bypass_plugins: bool = False
    ) -> Dict[NodeIndex, Attributes]: ...
    def replace_node_attributes(
        self, node_index: NodeIndexInputList, attributes: AttributesInput
    ) -> None: ...
    def update_node_attribute(
        self,
        node_index: NodeIndexInputList,
        attribute: GraphRecordAttribute,
        value: GraphRecordValue,
    ) -> None: ...
    def remove_node_attribute(
        self, node_index: NodeIndexInputList, attribute: GraphRecordAttribute
    ) -> None: ...
    def add_nodes(
        self, nodes: Sequence[NodeTuple], bypass_plugins: bool = False
    ) -> None: ...
    def add_nodes_with_group(
        self, nodes: Sequence[NodeTuple], group: Group, bypass_plugins: bool = False
    ) -> None: ...
    def add_nodes_dataframes(
        self,
        nodes_dataframe: List[PolarsNodeDataFrameInput],
        bypass_plugins: bool = False,
    ) -> None: ...
    def add_nodes_dataframes_with_group(
        self,
        nodes_dataframe: List[PolarsNodeDataFrameInput],
        group: Group,
        bypass_plugins: bool = False,
    ) -> None: ...
    def remove_edges(
        self, edge_index: EdgeIndexInputList, bypass_plugins: bool = False
    ) -> Dict[EdgeIndex, Attributes]: ...
    def replace_edge_attributes(
        self, edge_index: EdgeIndexInputList, attributes: AttributesInput
    ) -> None: ...
    def update_edge_attribute(
        self,
        edge_index: EdgeIndexInputList,
        attribute: GraphRecordAttribute,
        value: GraphRecordValue,
    ) -> None: ...
    def remove_edge_attribute(
        self, edge_index: EdgeIndexInputList, attribute: GraphRecordAttribute
    ) -> None: ...
    def add_edges(
        self, edges: Sequence[EdgeTuple], bypass_plugins: bool = False
    ) -> List[EdgeIndex]: ...
    def add_edges_with_group(
        self, edges: Sequence[EdgeTuple], group: Group, bypass_plugins: bool = False
    ) -> List[EdgeIndex]: ...
    def add_edges_dataframes(
        self,
        edges_dataframe: List[PolarsEdgeDataFrameInput],
        bypass_plugins: bool = False,
    ) -> List[EdgeIndex]: ...
    def add_edges_dataframes_with_group(
        self,
        edges_dataframe: List[PolarsEdgeDataFrameInput],
        group: Group,
        bypass_plugins: bool = False,
    ) -> List[EdgeIndex]: ...
    def add_group(
        self,
        group: Group,
        node_indices_to_add: Optional[NodeIndexInputList],
        edge_indices_to_add: Optional[EdgeIndexInputList],
        bypass_plugins: bool = False,
    ) -> None: ...
    def remove_groups(
        self, group: GroupInputList, bypass_plugins: bool = False
    ) -> None: ...
    def add_nodes_to_group(
        self, group: Group, node_index: NodeIndexInputList, bypass_plugins: bool = False
    ) -> None: ...
    def add_edges_to_group(
        self, group: Group, edge_index: EdgeIndexInputList, bypass_plugins: bool = False
    ) -> None: ...
    def remove_nodes_from_group(
        self, group: Group, node_index: NodeIndexInputList, bypass_plugins: bool = False
    ) -> None: ...
    def remove_edges_from_group(
        self, group: Group, edge_index: EdgeIndexInputList, bypass_plugins: bool = False
    ) -> None: ...
    def nodes_in_group(self, group: GroupInputList) -> Dict[Group, List[NodeIndex]]: ...
    def ungrouped_nodes(self) -> List[NodeIndex]: ...
    def edges_in_group(self, group: GroupInputList) -> Dict[Group, List[EdgeIndex]]: ...
    def ungrouped_edges(self) -> List[EdgeIndex]: ...
    def groups_of_node(
        self, node_index: NodeIndexInputList
    ) -> Dict[NodeIndex, List[Group]]: ...
    def groups_of_edge(
        self, edge_index: EdgeIndexInputList
    ) -> Dict[EdgeIndex, List[Group]]: ...
    def node_count(self) -> int: ...
    def edge_count(self) -> int: ...
    def group_count(self) -> int: ...
    def contains_node(self, node_index: NodeIndex) -> bool: ...
    def contains_edge(self, edge_index: EdgeIndex) -> bool: ...
    def contains_group(self, group: Group) -> bool: ...
    def neighbors_outgoing(
        self, node_indices: NodeIndexInputList
    ) -> Dict[NodeIndex, List[NodeIndex]]: ...
    def neighbors_incoming(
        self, node_indices: NodeIndexInputList
    ) -> Dict[NodeIndex, List[NodeIndex]]: ...
    def neighbors_undirected(
        self, node_indices: NodeIndexInputList
    ) -> Dict[NodeIndex, List[NodeIndex]]: ...
    def clear(self, bypass_plugins: bool = False) -> None: ...
    def query_nodes(
        self, query: Callable[[PyNodeOperand], PyQueryReturnOperand]
    ) -> QueryResult: ...
    def query_edges(
        self, query: Callable[[PyEdgeOperand], PyQueryReturnOperand]
    ) -> QueryResult: ...
    def clone(self) -> PyGraphRecord: ...
    def overview(self, truncate_details: Optional[int]) -> PyOverview: ...
    def group_overview(
        self, group: Group, truncate_details: Optional[int]
    ) -> PyGroupOverview: ...
