import os
from typing import (
    Any,
    ClassVar,
    Dict,
    Iterable,
    List,
    Optional,
    Protocol,
    Tuple,
    TypeAlias,
    TypedDict,
    TypeVar,
    Union,
)

import polars as pl

from graphrecords._graphrecords.overview import PyGroupOverview, PyOverview
from graphrecords._graphrecords.querying import PyArgument, PyExpression, PySeries
from graphrecords._graphrecords.schema import PySchema
from graphrecords.types import (
    AttributeName,
    Attributes,
    GroupIndex,
    NodeIndex,
    PluginName,
    Value,
)

class _NodeCollector(Protocol):
    def collect_nodes(self) -> Iterable[Tuple[NodeIndex, Attributes]]: ...

class _EdgeCollector(Protocol):
    def collect_edges(self) -> Iterable[Tuple[NodeIndex, NodeIndex, Attributes]]: ...

class _ArrowStream(Protocol):
    def __arrow_c_stream__(
        self, requested_schema: Optional[object] = None
    ) -> object: ...

_T = TypeVar("_T", covariant=True)

class _Writer(Protocol[_T]):
    def write(self, py_record: PyGraphRecord) -> _T: ...

NodeSource: TypeAlias = Union[
    Iterable[Tuple[NodeIndex, Attributes]],
    Tuple[pl.DataFrame, str],
    Tuple[_ArrowStream, str],
    _NodeCollector,
]
EdgeSource: TypeAlias = Union[
    Iterable[Tuple[NodeIndex, NodeIndex, Attributes]],
    Tuple[pl.DataFrame, str, str],
    Tuple[_ArrowStream, str, str],
    _EdgeCollector,
]
MultipleNodeSelection: TypeAlias = Union[
    NodeIndex,
    Iterable[NodeIndex],
    PyExpression,
    PySeries,
    PyArgument,
]
MultipleEdgeSelection: TypeAlias = Union[
    PyEdgeIndex,
    Iterable[PyEdgeIndex],
    PyExpression,
    PySeries,
    PyArgument,
]
MultipleGroupSelection: TypeAlias = Union[
    GroupIndex,
    Iterable[GroupIndex],
    PyExpression,
    PySeries,
    PyArgument,
]
SingleNodeSelection: TypeAlias = Union[NodeIndex, PyExpression, PySeries]
SingleGroupSelection: TypeAlias = Union[GroupIndex, PyExpression, PySeries]

class PyPolarsTables(TypedDict):
    nodes: pl.DataFrame
    edges: pl.DataFrame

class PyPolarsExport(TypedDict):
    ungrouped: PyPolarsTables
    groups: Dict[GroupIndex, PyPolarsTables]

class PyArrowTables(TypedDict):
    nodes: PyRecordBatch
    edges: PyRecordBatch

class PyArrowExport(TypedDict):
    ungrouped: PyArrowTables
    groups: Dict[GroupIndex, PyArrowTables]

class PyEdgeDirection:
    Incoming: PyEdgeDirection
    Outgoing: PyEdgeDirection
    Both: PyEdgeDirection

    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class PyOnConflict:
    Raise: PyOnConflict
    KeepSelf: PyOnConflict
    KeepOther: PyOnConflict

    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class PyEdgeIndex:
    @staticmethod
    def _from_bytes(data: bytes) -> PyEdgeIndex: ...
    def __reduce__(self) -> Tuple[Any, Tuple[bytes]]: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class PyNodeView:
    def index(self) -> NodeIndex: ...
    def attribute(self, attribute_name: AttributeName) -> Value: ...
    def attributes(self) -> Attributes: ...
    def groups(self) -> List[GroupIndex]: ...
    def edges(self, direction: PyEdgeDirection = ...) -> List[PyEdgeIndex]: ...
    def neighbors(self, direction: PyEdgeDirection = ...) -> List[NodeIndex]: ...
    def degree(self, direction: PyEdgeDirection = ...) -> int: ...
    def edges_to(
        self, target: SingleNodeSelection, direction: PyEdgeDirection = ...
    ) -> List[PyEdgeIndex]: ...

class PyEdgeView:
    def index(self) -> PyEdgeIndex: ...
    def source(self) -> NodeIndex: ...
    def target(self) -> NodeIndex: ...
    def attribute(self, attribute_name: AttributeName) -> Value: ...
    def attributes(self) -> Attributes: ...
    def groups(self) -> List[GroupIndex]: ...

class PyGroupView:
    def index(self) -> GroupIndex: ...
    def nodes(self) -> List[NodeIndex]: ...
    def edges(self) -> List[PyEdgeIndex]: ...
    def node_count(self) -> int: ...
    def edge_count(self) -> int: ...

class PyRecordBatch:
    def __arrow_c_array__(
        self, requested_schema: Optional[object] = None
    ) -> Tuple[object, object]: ...
    def __arrow_c_stream__(
        self, requested_schema: Optional[object] = None
    ) -> object: ...
    def __len__(self) -> int: ...

class PyGraphRecord:
    plugins: List[PluginName]
    plugin_entries: Dict[PluginName, object]
    schema: PySchema

    def __init__(self) -> None: ...
    @staticmethod
    def with_schema(schema: PySchema) -> PyGraphRecord: ...
    @staticmethod
    def from_ron(path: Union[str, os.PathLike[str]]) -> PyGraphRecord: ...
    def add_plugin(self, name: PluginName, plugin: object) -> PyGraphRecord: ...
    def remove_plugin(self, name: PluginName) -> PyGraphRecord: ...
    def add_nodes(self, source: NodeSource) -> PyGraphRecord: ...
    def add_node(
        self, node_index: SingleNodeSelection, attributes: Attributes
    ) -> PyGraphRecord: ...
    def add_nodes_in_group(
        self, source: NodeSource, group_index: SingleGroupSelection
    ) -> PyGraphRecord: ...
    def add_node_in_group(
        self,
        node_index: SingleNodeSelection,
        attributes: Attributes,
        group_index: SingleGroupSelection,
    ) -> PyGraphRecord: ...
    def add_edges(self, source: EdgeSource) -> PyGraphRecord: ...
    def add_edge(
        self,
        source_node_index: SingleNodeSelection,
        target_node_index: SingleNodeSelection,
        attributes: Attributes,
    ) -> PyGraphRecord: ...
    def add_edges_in_group(
        self, source: EdgeSource, group_index: SingleGroupSelection
    ) -> PyGraphRecord: ...
    def add_edge_in_group(
        self,
        source_node_index: SingleNodeSelection,
        target_node_index: SingleNodeSelection,
        attributes: Attributes,
        group_index: SingleGroupSelection,
    ) -> PyGraphRecord: ...
    def remove_nodes(self, node_indices: MultipleNodeSelection) -> PyGraphRecord: ...
    def remove_edges(self, edge_indices: MultipleEdgeSelection) -> PyGraphRecord: ...
    def keep_nodes(self, node_indices: MultipleNodeSelection) -> PyGraphRecord: ...
    def keep_edges(self, edge_indices: MultipleEdgeSelection) -> PyGraphRecord: ...
    def keep_groups(self, group_indices: MultipleGroupSelection) -> PyGraphRecord: ...
    def intersect(self, other: PyGraphRecord) -> PyGraphRecord: ...
    def difference(self, other: PyGraphRecord) -> PyGraphRecord: ...
    def merge(
        self, other: PyGraphRecord, on_conflict: PyOnConflict = ...
    ) -> PyGraphRecord: ...
    def set_node_attributes(
        self, node_indices: MultipleNodeSelection, attributes: Attributes
    ) -> PyGraphRecord: ...
    def replace_node_attributes(
        self, node_indices: MultipleNodeSelection, attributes: Attributes
    ) -> PyGraphRecord: ...
    def remove_node_attributes(
        self,
        node_indices: MultipleNodeSelection,
        attribute_names: Iterable[AttributeName],
    ) -> PyGraphRecord: ...
    def set_edge_attributes(
        self, edge_indices: MultipleEdgeSelection, attributes: Attributes
    ) -> PyGraphRecord: ...
    def replace_edge_attributes(
        self, edge_indices: MultipleEdgeSelection, attributes: Attributes
    ) -> PyGraphRecord: ...
    def remove_edge_attributes(
        self,
        edge_indices: MultipleEdgeSelection,
        attribute_names: Iterable[AttributeName],
    ) -> PyGraphRecord: ...
    def add_group(self, group_index: SingleGroupSelection) -> PyGraphRecord: ...
    def remove_groups(self, group_indices: MultipleGroupSelection) -> PyGraphRecord: ...
    def add_nodes_to_group(
        self, node_indices: MultipleNodeSelection, group_index: SingleGroupSelection
    ) -> PyGraphRecord: ...
    def remove_nodes_from_group(
        self, node_indices: MultipleNodeSelection, group_index: SingleGroupSelection
    ) -> PyGraphRecord: ...
    def add_edges_to_group(
        self, edge_indices: MultipleEdgeSelection, group_index: SingleGroupSelection
    ) -> PyGraphRecord: ...
    def remove_edges_from_group(
        self, edge_indices: MultipleEdgeSelection, group_index: SingleGroupSelection
    ) -> PyGraphRecord: ...
    def set_schema(self, schema: PySchema) -> PyGraphRecord: ...
    def freeze_schema(self) -> PyGraphRecord: ...
    def unfreeze_schema(self) -> PyGraphRecord: ...
    def clear(self) -> PyGraphRecord: ...
    def compact(self) -> PyGraphRecord: ...
    def node_count(self) -> int: ...
    def edge_count(self) -> int: ...
    def group_count(self) -> int: ...
    def contains_node(self, node_index: NodeIndex) -> bool: ...
    def contains_edge(self, edge_index: PyEdgeIndex) -> bool: ...
    def contains_group(self, group_index: GroupIndex) -> bool: ...
    def node_indices(self) -> List[NodeIndex]: ...
    def edge_indices(self) -> List[PyEdgeIndex]: ...
    def group_indices(self) -> List[GroupIndex]: ...
    def nodes(self) -> PySeries: ...
    def edges(self) -> PySeries: ...
    def groups(self) -> PySeries: ...
    def query(self, expression: PyExpression) -> PySeries: ...
    def node(self, node_index: NodeIndex) -> PyNodeView: ...
    def edge(self, edge_index: PyEdgeIndex) -> PyEdgeView: ...
    def group(self, group_index: GroupIndex) -> PyGroupView: ...
    def export(self, writer: _Writer[_T]) -> _T: ...
    def to_polars(self) -> PyPolarsExport: ...
    def to_arrow(self) -> PyArrowExport: ...
    def to_ron(self, path: Union[str, os.PathLike[str]]) -> None: ...
    def overview(self, truncate_details: Optional[int] = None) -> PyOverview: ...
    def group_overview(
        self, group_index: GroupIndex, truncate_details: Optional[int] = None
    ) -> PyGroupOverview: ...
    @staticmethod
    def _from_bytes(data: bytes) -> PyGraphRecord: ...
    def _to_bytes(self) -> bytes: ...
    @staticmethod
    def _restore(
        data: bytes, plugins: List[Tuple[PluginName, Any]]
    ) -> PyGraphRecord: ...
    def __reduce__(self) -> Tuple[Any, Tuple[Any, ...]]: ...
    def __eq__(self, other: object) -> bool: ...
    __hash__: ClassVar[None]
    def __copy__(self) -> PyGraphRecord: ...
    def __deepcopy__(self, memo: Optional[Dict[int, Any]] = None) -> PyGraphRecord: ...
