class NodeHandle:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class GroupHandle:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class AttributeHandle:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
