from typing import List, Optional, Tuple

from graphrecords._graphrecords.schema import PySchema
from graphrecords.types import (
    Attributes,
    EdgeIndex,
    Group,
    GroupHandle,
    NodeHandle,
    NodeIndex,
    PolarsEdgeDataFrameInput,
    PolarsNodeDataFrameInput,
)

class PyPreSetSchemaContext:
    def __init__(self, schema: PySchema) -> None: ...
    @property
    def schema(self) -> PySchema: ...

class PyPreAddNodeContext:
    def __init__(self, node_index: NodeIndex, attributes: Attributes) -> None: ...
    @property
    def node_index(self) -> NodeIndex: ...
    @property
    def attributes(self) -> Attributes: ...

class PyPostAddNodeContext:
    def __init__(self, node_index: NodeIndex) -> None: ...
    @property
    def node_index(self) -> NodeIndex: ...

class PyPreAddNodeWithGroupContext:
    def __init__(
        self,
        node_index: NodeIndex,
        attributes: Attributes,
        group_handle: GroupHandle,
    ) -> None: ...
    @property
    def node_index(self) -> NodeIndex: ...
    @property
    def attributes(self) -> Attributes: ...
    @property
    def group_handle(self) -> GroupHandle: ...

class PyPostAddNodeWithGroupContext:
    def __init__(self, node_index: NodeIndex, group_handle: GroupHandle) -> None: ...
    @property
    def node_index(self) -> NodeIndex: ...
    @property
    def group_handle(self) -> GroupHandle: ...

class PyPreRemoveNodeContext:
    def __init__(self, node_handle: NodeHandle) -> None: ...
    @property
    def node_handle(self) -> NodeHandle: ...

class PyPostRemoveNodeContext:
    def __init__(self, node_handle: NodeHandle) -> None: ...
    @property
    def node_handle(self) -> NodeHandle: ...

class PyPreAddNodesContext:
    def __init__(self, nodes: List[Tuple[NodeIndex, Attributes]]) -> None: ...
    @property
    def nodes(self) -> List[Tuple[NodeIndex, Attributes]]: ...

class PyPostAddNodesContext:
    def __init__(self, nodes: List[Tuple[NodeIndex, Attributes]]) -> None: ...
    @property
    def nodes(self) -> List[Tuple[NodeIndex, Attributes]]: ...

class PyPreAddNodesWithGroupContext:
    def __init__(
        self,
        nodes: List[Tuple[NodeIndex, Attributes]],
        group_handle: GroupHandle,
    ) -> None: ...
    @property
    def nodes(self) -> List[Tuple[NodeIndex, Attributes]]: ...
    @property
    def group_handle(self) -> GroupHandle: ...

class PyPostAddNodesWithGroupContext:
    def __init__(
        self,
        nodes: List[Tuple[NodeIndex, Attributes]],
        group_handle: GroupHandle,
    ) -> None: ...
    @property
    def nodes(self) -> List[Tuple[NodeIndex, Attributes]]: ...
    @property
    def group_handle(self) -> GroupHandle: ...

class PyPreAddNodesDataframesContext:
    def __init__(self, nodes_dataframes: List[PolarsNodeDataFrameInput]) -> None: ...
    @property
    def nodes_dataframes(self) -> List[PolarsNodeDataFrameInput]: ...

class PyPostAddNodesDataframesContext:
    def __init__(self, nodes_dataframes: List[PolarsNodeDataFrameInput]) -> None: ...
    @property
    def nodes_dataframes(self) -> List[PolarsNodeDataFrameInput]: ...

class PyPreAddNodesDataframesWithGroupContext:
    def __init__(
        self,
        nodes_dataframes: List[PolarsNodeDataFrameInput],
        group_handle: GroupHandle,
    ) -> None: ...
    @property
    def nodes_dataframes(self) -> List[PolarsNodeDataFrameInput]: ...
    @property
    def group_handle(self) -> GroupHandle: ...

class PyPostAddNodesDataframesWithGroupContext:
    def __init__(
        self,
        nodes_dataframes: List[PolarsNodeDataFrameInput],
        group_handle: GroupHandle,
    ) -> None: ...
    @property
    def nodes_dataframes(self) -> List[PolarsNodeDataFrameInput]: ...
    @property
    def group_handle(self) -> GroupHandle: ...

class PyPreAddEdgeContext:
    def __init__(
        self,
        source_node_handle: NodeHandle,
        target_node_handle: NodeHandle,
        attributes: Attributes,
    ) -> None: ...
    @property
    def source_node_handle(self) -> NodeHandle: ...
    @property
    def target_node_handle(self) -> NodeHandle: ...
    @property
    def attributes(self) -> Attributes: ...

class PyPostAddEdgeContext:
    def __init__(self, edge_index: EdgeIndex) -> None: ...
    @property
    def edge_index(self) -> EdgeIndex: ...

class PyPreAddEdgeWithGroupContext:
    def __init__(
        self,
        source_node_handle: NodeHandle,
        target_node_handle: NodeHandle,
        attributes: Attributes,
        group_handle: GroupHandle,
    ) -> None: ...
    @property
    def source_node_handle(self) -> NodeHandle: ...
    @property
    def target_node_handle(self) -> NodeHandle: ...
    @property
    def attributes(self) -> Attributes: ...
    @property
    def group_handle(self) -> GroupHandle: ...

class PyPostAddEdgeWithGroupContext:
    def __init__(self, edge_index: EdgeIndex, group_handle: GroupHandle) -> None: ...
    @property
    def edge_index(self) -> EdgeIndex: ...
    @property
    def group_handle(self) -> GroupHandle: ...

class PyPreRemoveEdgeContext:
    def __init__(self, edge_index: EdgeIndex) -> None: ...
    @property
    def edge_index(self) -> EdgeIndex: ...

class PyPostRemoveEdgeContext:
    def __init__(self, edge_index: EdgeIndex) -> None: ...
    @property
    def edge_index(self) -> EdgeIndex: ...

class PyPreAddEdgesContext:
    def __init__(
        self, edges: List[Tuple[NodeHandle, NodeHandle, Attributes]]
    ) -> None: ...
    @property
    def edges(self) -> List[Tuple[NodeHandle, NodeHandle, Attributes]]: ...

class PyPostAddEdgesContext:
    def __init__(self, edge_indices: List[EdgeIndex]) -> None: ...
    @property
    def edge_indices(self) -> List[EdgeIndex]: ...

class PyPreAddEdgesWithGroupContext:
    def __init__(
        self,
        edges: List[Tuple[NodeHandle, NodeHandle, Attributes]],
        group_handle: GroupHandle,
    ) -> None: ...
    @property
    def edges(self) -> List[Tuple[NodeHandle, NodeHandle, Attributes]]: ...
    @property
    def group_handle(self) -> GroupHandle: ...

class PyPostAddEdgesWithGroupContext:
    def __init__(
        self, edge_indices: List[EdgeIndex], group_handle: GroupHandle
    ) -> None: ...
    @property
    def edge_indices(self) -> List[EdgeIndex]: ...
    @property
    def group_handle(self) -> GroupHandle: ...

class PyPreAddEdgesDataframesContext:
    def __init__(self, edges_dataframes: List[PolarsEdgeDataFrameInput]) -> None: ...
    @property
    def edges_dataframes(self) -> List[PolarsEdgeDataFrameInput]: ...

class PyPostAddEdgesDataframesContext:
    def __init__(self, edges_dataframes: List[PolarsEdgeDataFrameInput]) -> None: ...
    @property
    def edges_dataframes(self) -> List[PolarsEdgeDataFrameInput]: ...

class PyPreAddEdgesDataframesWithGroupContext:
    def __init__(
        self,
        edges_dataframes: List[PolarsEdgeDataFrameInput],
        group_handle: GroupHandle,
    ) -> None: ...
    @property
    def edges_dataframes(self) -> List[PolarsEdgeDataFrameInput]: ...
    @property
    def group_handle(self) -> GroupHandle: ...

class PyPostAddEdgesDataframesWithGroupContext:
    def __init__(
        self,
        edges_dataframes: List[PolarsEdgeDataFrameInput],
        group_handle: GroupHandle,
    ) -> None: ...
    @property
    def edges_dataframes(self) -> List[PolarsEdgeDataFrameInput]: ...
    @property
    def group_handle(self) -> GroupHandle: ...

class PyPreAddGroupContext:
    def __init__(
        self,
        group: Group,
        node_handles: Optional[List[NodeHandle]],
        edge_indices: Optional[List[EdgeIndex]],
    ) -> None: ...
    @property
    def group(self) -> Group: ...
    @property
    def node_handles(self) -> Optional[List[NodeHandle]]: ...
    @property
    def edge_indices(self) -> Optional[List[EdgeIndex]]: ...

class PyPostAddGroupContext:
    def __init__(
        self,
        group: Group,
        node_handles: Optional[List[NodeHandle]],
        edge_indices: Optional[List[EdgeIndex]],
    ) -> None: ...
    @property
    def group(self) -> Group: ...
    @property
    def node_handles(self) -> Optional[List[NodeHandle]]: ...
    @property
    def edge_indices(self) -> Optional[List[EdgeIndex]]: ...

class PyPreRemoveGroupContext:
    def __init__(self, group_handle: GroupHandle) -> None: ...
    @property
    def group_handle(self) -> GroupHandle: ...

class PyPostRemoveGroupContext:
    def __init__(self, group_handle: GroupHandle) -> None: ...
    @property
    def group_handle(self) -> GroupHandle: ...

class PyPreAddNodeToGroupContext:
    def __init__(self, group_handle: GroupHandle, node_handle: NodeHandle) -> None: ...
    @property
    def group_handle(self) -> GroupHandle: ...
    @property
    def node_handle(self) -> NodeHandle: ...

class PyPostAddNodeToGroupContext:
    def __init__(self, group_handle: GroupHandle, node_handle: NodeHandle) -> None: ...
    @property
    def group_handle(self) -> GroupHandle: ...
    @property
    def node_handle(self) -> NodeHandle: ...

class PyPreAddNodeToGroupsContext:
    def __init__(
        self, group_handles: List[GroupHandle], node_handle: NodeHandle
    ) -> None: ...
    @property
    def group_handles(self) -> List[GroupHandle]: ...
    @property
    def node_handle(self) -> NodeHandle: ...

class PyPostAddNodeToGroupsContext:
    def __init__(
        self, group_handles: List[GroupHandle], node_handle: NodeHandle
    ) -> None: ...
    @property
    def group_handles(self) -> List[GroupHandle]: ...
    @property
    def node_handle(self) -> NodeHandle: ...

class PyPreAddNodesToGroupsContext:
    def __init__(
        self, group_handles: List[GroupHandle], node_handles: List[NodeHandle]
    ) -> None: ...
    @property
    def group_handles(self) -> List[GroupHandle]: ...
    @property
    def node_handles(self) -> List[NodeHandle]: ...

class PyPostAddNodesToGroupsContext:
    def __init__(
        self, group_handles: List[GroupHandle], node_handles: List[NodeHandle]
    ) -> None: ...
    @property
    def group_handles(self) -> List[GroupHandle]: ...
    @property
    def node_handles(self) -> List[NodeHandle]: ...

class PyPreAddEdgeToGroupContext:
    def __init__(self, group_handle: GroupHandle, edge_index: EdgeIndex) -> None: ...
    @property
    def group_handle(self) -> GroupHandle: ...
    @property
    def edge_index(self) -> EdgeIndex: ...

class PyPostAddEdgeToGroupContext:
    def __init__(self, group_handle: GroupHandle, edge_index: EdgeIndex) -> None: ...
    @property
    def group_handle(self) -> GroupHandle: ...
    @property
    def edge_index(self) -> EdgeIndex: ...

class PyPreAddEdgeToGroupsContext:
    def __init__(
        self, group_handles: List[GroupHandle], edge_index: EdgeIndex
    ) -> None: ...
    @property
    def group_handles(self) -> List[GroupHandle]: ...
    @property
    def edge_index(self) -> EdgeIndex: ...

class PyPostAddEdgeToGroupsContext:
    def __init__(
        self, group_handles: List[GroupHandle], edge_index: EdgeIndex
    ) -> None: ...
    @property
    def group_handles(self) -> List[GroupHandle]: ...
    @property
    def edge_index(self) -> EdgeIndex: ...

class PyPreAddEdgesToGroupsContext:
    def __init__(
        self, group_handles: List[GroupHandle], edge_indices: List[EdgeIndex]
    ) -> None: ...
    @property
    def group_handles(self) -> List[GroupHandle]: ...
    @property
    def edge_indices(self) -> List[EdgeIndex]: ...

class PyPostAddEdgesToGroupsContext:
    def __init__(
        self, group_handles: List[GroupHandle], edge_indices: List[EdgeIndex]
    ) -> None: ...
    @property
    def group_handles(self) -> List[GroupHandle]: ...
    @property
    def edge_indices(self) -> List[EdgeIndex]: ...

class PyPreRemoveNodeFromGroupContext:
    def __init__(self, group_handle: GroupHandle, node_handle: NodeHandle) -> None: ...
    @property
    def group_handle(self) -> GroupHandle: ...
    @property
    def node_handle(self) -> NodeHandle: ...

class PyPostRemoveNodeFromGroupContext:
    def __init__(self, group_handle: GroupHandle, node_handle: NodeHandle) -> None: ...
    @property
    def group_handle(self) -> GroupHandle: ...
    @property
    def node_handle(self) -> NodeHandle: ...

class PyPreRemoveNodeFromGroupsContext:
    def __init__(
        self, group_handles: List[GroupHandle], node_handle: NodeHandle
    ) -> None: ...
    @property
    def group_handles(self) -> List[GroupHandle]: ...
    @property
    def node_handle(self) -> NodeHandle: ...

class PyPostRemoveNodeFromGroupsContext:
    def __init__(
        self, group_handles: List[GroupHandle], node_handle: NodeHandle
    ) -> None: ...
    @property
    def group_handles(self) -> List[GroupHandle]: ...
    @property
    def node_handle(self) -> NodeHandle: ...

class PyPreRemoveNodesFromGroupsContext:
    def __init__(
        self, group_handles: List[GroupHandle], node_handles: List[NodeHandle]
    ) -> None: ...
    @property
    def group_handles(self) -> List[GroupHandle]: ...
    @property
    def node_handles(self) -> List[NodeHandle]: ...

class PyPostRemoveNodesFromGroupsContext:
    def __init__(
        self, group_handles: List[GroupHandle], node_handles: List[NodeHandle]
    ) -> None: ...
    @property
    def group_handles(self) -> List[GroupHandle]: ...
    @property
    def node_handles(self) -> List[NodeHandle]: ...

class PyPreRemoveEdgeFromGroupContext:
    def __init__(self, group_handle: GroupHandle, edge_index: EdgeIndex) -> None: ...
    @property
    def group_handle(self) -> GroupHandle: ...
    @property
    def edge_index(self) -> EdgeIndex: ...

class PyPostRemoveEdgeFromGroupContext:
    def __init__(self, group_handle: GroupHandle, edge_index: EdgeIndex) -> None: ...
    @property
    def group_handle(self) -> GroupHandle: ...
    @property
    def edge_index(self) -> EdgeIndex: ...

class PyPreRemoveEdgeFromGroupsContext:
    def __init__(
        self, group_handles: List[GroupHandle], edge_index: EdgeIndex
    ) -> None: ...
    @property
    def group_handles(self) -> List[GroupHandle]: ...
    @property
    def edge_index(self) -> EdgeIndex: ...

class PyPostRemoveEdgeFromGroupsContext:
    def __init__(
        self, group_handles: List[GroupHandle], edge_index: EdgeIndex
    ) -> None: ...
    @property
    def group_handles(self) -> List[GroupHandle]: ...
    @property
    def edge_index(self) -> EdgeIndex: ...

class PyPreRemoveEdgesFromGroupsContext:
    def __init__(
        self, group_handles: List[GroupHandle], edge_indices: List[EdgeIndex]
    ) -> None: ...
    @property
    def group_handles(self) -> List[GroupHandle]: ...
    @property
    def edge_indices(self) -> List[EdgeIndex]: ...

class PyPostRemoveEdgesFromGroupsContext:
    def __init__(
        self, group_handles: List[GroupHandle], edge_indices: List[EdgeIndex]
    ) -> None: ...
    @property
    def group_handles(self) -> List[GroupHandle]: ...
    @property
    def edge_indices(self) -> List[EdgeIndex]: ...

class PyPreAddNodeWithGroupsContext:
    def __init__(
        self,
        node_index: NodeIndex,
        attributes: Attributes,
        group_handles: List[GroupHandle],
    ) -> None: ...
    @property
    def node_index(self) -> NodeIndex: ...
    @property
    def attributes(self) -> Attributes: ...
    @property
    def group_handles(self) -> List[GroupHandle]: ...

class PyPostAddNodeWithGroupsContext:
    def __init__(
        self, node_index: NodeIndex, group_handles: List[GroupHandle]
    ) -> None: ...
    @property
    def node_index(self) -> NodeIndex: ...
    @property
    def group_handles(self) -> List[GroupHandle]: ...

class PyPreAddEdgeWithGroupsContext:
    def __init__(
        self,
        source_node_handle: NodeHandle,
        target_node_handle: NodeHandle,
        attributes: Attributes,
        group_handles: List[GroupHandle],
    ) -> None: ...
    @property
    def source_node_handle(self) -> NodeHandle: ...
    @property
    def target_node_handle(self) -> NodeHandle: ...
    @property
    def attributes(self) -> Attributes: ...
    @property
    def group_handles(self) -> List[GroupHandle]: ...

class PyPostAddEdgeWithGroupsContext:
    def __init__(
        self, edge_index: EdgeIndex, group_handles: List[GroupHandle]
    ) -> None: ...
    @property
    def edge_index(self) -> EdgeIndex: ...
    @property
    def group_handles(self) -> List[GroupHandle]: ...

class PyPreAddNodesWithGroupsContext:
    def __init__(
        self,
        nodes: List[Tuple[NodeIndex, Attributes]],
        group_handles: List[GroupHandle],
    ) -> None: ...
    @property
    def nodes(self) -> List[Tuple[NodeIndex, Attributes]]: ...
    @property
    def group_handles(self) -> List[GroupHandle]: ...

class PyPostAddNodesWithGroupsContext:
    def __init__(
        self,
        nodes: List[Tuple[NodeIndex, Attributes]],
        group_handles: List[GroupHandle],
    ) -> None: ...
    @property
    def nodes(self) -> List[Tuple[NodeIndex, Attributes]]: ...
    @property
    def group_handles(self) -> List[GroupHandle]: ...

class PyPreAddEdgesWithGroupsContext:
    def __init__(
        self,
        edges: List[Tuple[NodeHandle, NodeHandle, Attributes]],
        group_handles: List[GroupHandle],
    ) -> None: ...
    @property
    def edges(self) -> List[Tuple[NodeHandle, NodeHandle, Attributes]]: ...
    @property
    def group_handles(self) -> List[GroupHandle]: ...

class PyPostAddEdgesWithGroupsContext:
    def __init__(
        self, edge_indices: List[EdgeIndex], group_handles: List[GroupHandle]
    ) -> None: ...
    @property
    def edge_indices(self) -> List[EdgeIndex]: ...
    @property
    def group_handles(self) -> List[GroupHandle]: ...

class PyPreAddNodesDataframesWithGroupsContext:
    def __init__(
        self,
        nodes_dataframes: List[PolarsNodeDataFrameInput],
        group_handles: List[GroupHandle],
    ) -> None: ...
    @property
    def nodes_dataframes(self) -> List[PolarsNodeDataFrameInput]: ...
    @property
    def group_handles(self) -> List[GroupHandle]: ...

class PyPostAddNodesDataframesWithGroupsContext:
    def __init__(
        self,
        nodes_dataframes: List[PolarsNodeDataFrameInput],
        group_handles: List[GroupHandle],
    ) -> None: ...
    @property
    def nodes_dataframes(self) -> List[PolarsNodeDataFrameInput]: ...
    @property
    def group_handles(self) -> List[GroupHandle]: ...

class PyPreAddEdgesDataframesWithGroupsContext:
    def __init__(
        self,
        edges_dataframes: List[PolarsEdgeDataFrameInput],
        group_handles: List[GroupHandle],
    ) -> None: ...
    @property
    def edges_dataframes(self) -> List[PolarsEdgeDataFrameInput]: ...
    @property
    def group_handles(self) -> List[GroupHandle]: ...

class PyPostAddEdgesDataframesWithGroupsContext:
    def __init__(
        self,
        edges_dataframes: List[PolarsEdgeDataFrameInput],
        group_handles: List[GroupHandle],
    ) -> None: ...
    @property
    def edges_dataframes(self) -> List[PolarsEdgeDataFrameInput]: ...
    @property
    def group_handles(self) -> List[GroupHandle]: ...
