from typing import List, Optional, Tuple

from graphrecords._graphrecords.schema import PySchema
from graphrecords.types import (
    Attributes,
    EdgeIndex,
    Group,
    NodeIndex,
    PolarsEdgeDataFrameInput,
    PolarsNodeDataFrameInput,
)

class PyPreSetSchemaContext:
    def __init__(self, schema: PySchema) -> None: ...
    @property
    def schema(self) -> PySchema: ...

class PyPreAddNodeContext:
    def __init__(self, node_index: NodeIndex, attributes: Attributes) -> None: ...
    @property
    def node_index(self) -> NodeIndex: ...
    @property
    def attributes(self) -> Attributes: ...

class PyPostAddNodeContext:
    def __init__(self, node_index: NodeIndex) -> None: ...
    @property
    def node_index(self) -> NodeIndex: ...

class PyPreAddNodeWithGroupContext:
    def __init__(
        self, node_index: NodeIndex, attributes: Attributes, group: Group
    ) -> None: ...
    @property
    def node_index(self) -> NodeIndex: ...
    @property
    def attributes(self) -> Attributes: ...
    @property
    def group(self) -> Group: ...

class PyPostAddNodeWithGroupContext:
    def __init__(self, node_index: NodeIndex, group: Group) -> None: ...
    @property
    def node_index(self) -> NodeIndex: ...
    @property
    def group(self) -> Group: ...

class PyPreRemoveNodeContext:
    def __init__(self, node_index: NodeIndex) -> None: ...
    @property
    def node_index(self) -> NodeIndex: ...

class PyPostRemoveNodeContext:
    def __init__(self, node_index: NodeIndex) -> None: ...
    @property
    def node_index(self) -> NodeIndex: ...

class PyPreAddNodesContext:
    def __init__(self, nodes: List[Tuple[NodeIndex, Attributes]]) -> None: ...
    @property
    def nodes(self) -> List[Tuple[NodeIndex, Attributes]]: ...

class PyPostAddNodesContext:
    def __init__(self, nodes: List[Tuple[NodeIndex, Attributes]]) -> None: ...
    @property
    def nodes(self) -> List[Tuple[NodeIndex, Attributes]]: ...

class PyPreAddNodesWithGroupContext:
    def __init__(
        self, nodes: List[Tuple[NodeIndex, Attributes]], group: Group
    ) -> None: ...
    @property
    def nodes(self) -> List[Tuple[NodeIndex, Attributes]]: ...
    @property
    def group(self) -> Group: ...

class PyPostAddNodesWithGroupContext:
    def __init__(
        self, nodes: List[Tuple[NodeIndex, Attributes]], group: Group
    ) -> None: ...
    @property
    def nodes(self) -> List[Tuple[NodeIndex, Attributes]]: ...
    @property
    def group(self) -> Group: ...

class PyPreAddNodesDataframesContext:
    def __init__(self, nodes_dataframes: List[PolarsNodeDataFrameInput]) -> None: ...
    @property
    def nodes_dataframes(self) -> List[PolarsNodeDataFrameInput]: ...

class PyPostAddNodesDataframesContext:
    def __init__(self, nodes_dataframes: List[PolarsNodeDataFrameInput]) -> None: ...
    @property
    def nodes_dataframes(self) -> List[PolarsNodeDataFrameInput]: ...

class PyPreAddNodesDataframesWithGroupContext:
    def __init__(
        self, nodes_dataframes: List[PolarsNodeDataFrameInput], group: Group
    ) -> None: ...
    @property
    def nodes_dataframes(self) -> List[PolarsNodeDataFrameInput]: ...
    @property
    def group(self) -> Group: ...

class PyPostAddNodesDataframesWithGroupContext:
    def __init__(
        self, nodes_dataframes: List[PolarsNodeDataFrameInput], group: Group
    ) -> None: ...
    @property
    def nodes_dataframes(self) -> List[PolarsNodeDataFrameInput]: ...
    @property
    def group(self) -> Group: ...

class PyPreAddEdgeContext:
    def __init__(
        self,
        source_node_index: NodeIndex,
        target_node_index: NodeIndex,
        attributes: Attributes,
    ) -> None: ...
    @property
    def source_node_index(self) -> NodeIndex: ...
    @property
    def target_node_index(self) -> NodeIndex: ...
    @property
    def attributes(self) -> Attributes: ...

class PyPostAddEdgeContext:
    def __init__(self, edge_index: EdgeIndex) -> None: ...
    @property
    def edge_index(self) -> EdgeIndex: ...

class PyPreAddEdgeWithGroupContext:
    def __init__(
        self,
        source_node_index: NodeIndex,
        target_node_index: NodeIndex,
        attributes: Attributes,
        group: Group,
    ) -> None: ...
    @property
    def source_node_index(self) -> NodeIndex: ...
    @property
    def target_node_index(self) -> NodeIndex: ...
    @property
    def attributes(self) -> Attributes: ...
    @property
    def group(self) -> Group: ...

class PyPostAddEdgeWithGroupContext:
    def __init__(self, edge_index: EdgeIndex) -> None: ...
    @property
    def edge_index(self) -> EdgeIndex: ...

class PyPreRemoveEdgeContext:
    def __init__(self, edge_index: EdgeIndex) -> None: ...
    @property
    def edge_index(self) -> EdgeIndex: ...

class PyPostRemoveEdgeContext:
    def __init__(self, edge_index: EdgeIndex) -> None: ...
    @property
    def edge_index(self) -> EdgeIndex: ...

class PyPreAddEdgesContext:
    def __init__(
        self, edges: List[Tuple[NodeIndex, NodeIndex, Attributes]]
    ) -> None: ...
    @property
    def edges(self) -> List[Tuple[NodeIndex, NodeIndex, Attributes]]: ...

class PyPostAddEdgesContext:
    def __init__(self, edge_indices: List[EdgeIndex]) -> None: ...
    @property
    def edge_indices(self) -> List[EdgeIndex]: ...

class PyPreAddEdgesWithGroupContext:
    def __init__(
        self, edges: List[Tuple[NodeIndex, NodeIndex, Attributes]], group: Group
    ) -> None: ...
    @property
    def edges(self) -> List[Tuple[NodeIndex, NodeIndex, Attributes]]: ...
    @property
    def group(self) -> Group: ...

class PyPostAddEdgesWithGroupContext:
    def __init__(self, edge_indices: List[EdgeIndex]) -> None: ...
    @property
    def edge_indices(self) -> List[EdgeIndex]: ...

class PyPreAddEdgesDataframesContext:
    def __init__(self, edges_dataframes: List[PolarsEdgeDataFrameInput]) -> None: ...
    @property
    def edges_dataframes(self) -> List[PolarsEdgeDataFrameInput]: ...

class PyPostAddEdgesDataframesContext:
    def __init__(self, edges_dataframes: List[PolarsEdgeDataFrameInput]) -> None: ...
    @property
    def edges_dataframes(self) -> List[PolarsEdgeDataFrameInput]: ...

class PyPreAddEdgesDataframesWithGroupContext:
    def __init__(
        self, edges_dataframes: List[PolarsEdgeDataFrameInput], group: Group
    ) -> None: ...
    @property
    def edges_dataframes(self) -> List[PolarsEdgeDataFrameInput]: ...
    @property
    def group(self) -> Group: ...

class PyPostAddEdgesDataframesWithGroupContext:
    def __init__(
        self, edges_dataframes: List[PolarsEdgeDataFrameInput], group: Group
    ) -> None: ...
    @property
    def edges_dataframes(self) -> List[PolarsEdgeDataFrameInput]: ...
    @property
    def group(self) -> Group: ...

class PyPreAddGroupContext:
    def __init__(
        self,
        group: Group,
        node_indices: Optional[List[NodeIndex]],
        edge_indices: Optional[List[EdgeIndex]],
    ) -> None: ...
    @property
    def group(self) -> Group: ...
    @property
    def node_indices(self) -> Optional[List[NodeIndex]]: ...
    @property
    def edge_indices(self) -> Optional[List[EdgeIndex]]: ...

class PyPostAddGroupContext:
    def __init__(
        self,
        group: Group,
        node_indices: Optional[List[NodeIndex]],
        edge_indices: Optional[List[EdgeIndex]],
    ) -> None: ...
    @property
    def group(self) -> Group: ...
    @property
    def node_indices(self) -> Optional[List[NodeIndex]]: ...
    @property
    def edge_indices(self) -> Optional[List[EdgeIndex]]: ...

class PyPreRemoveGroupContext:
    def __init__(self, group: Group) -> None: ...
    @property
    def group(self) -> Group: ...

class PyPostRemoveGroupContext:
    def __init__(self, group: Group) -> None: ...
    @property
    def group(self) -> Group: ...

class PyPreAddNodeToGroupContext:
    def __init__(self, group: Group, node_index: NodeIndex) -> None: ...
    @property
    def group(self) -> Group: ...
    @property
    def node_index(self) -> NodeIndex: ...

class PyPostAddNodeToGroupContext:
    def __init__(self, group: Group, node_index: NodeIndex) -> None: ...
    @property
    def group(self) -> Group: ...
    @property
    def node_index(self) -> NodeIndex: ...

class PyPreAddEdgeToGroupContext:
    def __init__(self, group: Group, edge_index: EdgeIndex) -> None: ...
    @property
    def group(self) -> Group: ...
    @property
    def edge_index(self) -> EdgeIndex: ...

class PyPostAddEdgeToGroupContext:
    def __init__(self, group: Group, edge_index: EdgeIndex) -> None: ...
    @property
    def group(self) -> Group: ...
    @property
    def edge_index(self) -> EdgeIndex: ...

class PyPreRemoveNodeFromGroupContext:
    def __init__(self, group: Group, node_index: NodeIndex) -> None: ...
    @property
    def group(self) -> Group: ...
    @property
    def node_index(self) -> NodeIndex: ...

class PyPostRemoveNodeFromGroupContext:
    def __init__(self, group: Group, node_index: NodeIndex) -> None: ...
    @property
    def group(self) -> Group: ...
    @property
    def node_index(self) -> NodeIndex: ...

class PyPreRemoveEdgeFromGroupContext:
    def __init__(self, group: Group, edge_index: EdgeIndex) -> None: ...
    @property
    def group(self) -> Group: ...
    @property
    def edge_index(self) -> EdgeIndex: ...

class PyPostRemoveEdgeFromGroupContext:
    def __init__(self, group: Group, edge_index: EdgeIndex) -> None: ...
    @property
    def group(self) -> Group: ...
    @property
    def edge_index(self) -> EdgeIndex: ...
