from enum import Enum
from typing import Sequence, Union

from graphrecords.types import GraphRecordValue

class QueryError(Exception): ...
class InvalidMedianValueError(QueryError): ...
class InvalidStandardDeviationValueError(QueryError): ...
class InvalidVarianceValueError(QueryError): ...
class ArgumentAbsentError(QueryError): ...
class DivisionByZeroError(QueryError): ...
class ModuloByZeroError(QueryError): ...
class IncomparableValuesError(QueryError): ...
class IncomparableValuesAtError(QueryError): ...
class InvalidCastError(QueryError): ...
class InvalidTransitionError(QueryError): ...
class UnsupportedValueRoleError(QueryError): ...
class EvaluationCacheGraphRecordMismatchError(QueryError): ...
class InvalidPartitionBucketArityError(QueryError): ...
class MissingGroupAggregateError(QueryError): ...
class UnresolvedBucketFailuresError(QueryError): ...
class UnresolvedGroupKeyFailuresError(QueryError): ...
class DuplicateExpandedChildIndexError(QueryError): ...
class DuplicateIndexError(QueryError): ...
class NoChildIndexError(QueryError): ...
class IntegerOverflowError(QueryError): ...
class InvalidClipBoundsError(QueryError): ...
class NegativeLengthError(QueryError): ...
class NegativeSquareRootError(QueryError): ...
class NonIntegerValueError(QueryError): ...
class NonNumericValueError(QueryError): ...
class NonPositiveLogarithmError(QueryError): ...
class IncomparableIndicesError(QueryError): ...
class EmptySplitDelimiterError(QueryError): ...
class InvalidPaddingCharacterError(QueryError): ...
class InvalidRegexPatternError(QueryError): ...
class InvalidStringSliceError(QueryError): ...
class NonStringValueError(QueryError): ...
class StringLengthOverflowError(QueryError): ...
class StringPaddingOverflowError(QueryError): ...
class MissingAttributeError(QueryError): ...
class MissingTraversedAttributeError(QueryError): ...
class ExternalError(QueryError): ...
class GraphRecordError(QueryError): ...

class PyEdgeDirection(Enum):
    Incoming = ...
    Outgoing = ...
    Both = ...

class PyEdgeEndpointRole(Enum):
    Source = ...
    Target = ...

class PyFailureKind:
    @property
    def name(self) -> str: ...

class PyCastTarget(Enum):
    Bool = ...
    DateTime = ...
    Duration = ...
    Float = ...
    Int = ...
    String = ...

class PyValueTarget(Enum):
    Value = ...
    ValueIndex = ...
    AttributeName = ...
    AttributeNameIndex = ...
    NodeIndex = ...
    EdgeIndex = ...
    PositionalIndex = ...
    BoolIndex = ...
    Mask = ...
    FailureKind = ...
    FailureKindIndex = ...

class PyArgument: ...

class PyOperand:
    def on_missing_drop(self) -> PyArgument: ...
    def on_missing_replace(
        self, replacement: Union[PyOperand, PyArgument, GraphRecordValue, PyFailureKind]
    ) -> PyArgument: ...
    def cache(self) -> PyOperand: ...
    def filter(self, mask: Union[PyOperand, PyArgument, bool]) -> PyOperand: ...
    def and_(self, other: Union[PyOperand, PyArgument, bool]) -> PyOperand: ...
    def or_(self, other: Union[PyOperand, PyArgument, bool]) -> PyOperand: ...
    def xor(self, other: Union[PyOperand, PyArgument, bool]) -> PyOperand: ...
    def not_(self) -> PyOperand: ...
    def first(self) -> PyOperand: ...
    def last(self) -> PyOperand: ...
    def reverse_order(self) -> PyOperand: ...
    def shuffle(self) -> PyOperand: ...
    def unorder(self) -> PyOperand: ...
    def sort(self) -> PyOperand: ...
    def sort_by(
        self, key: Union[PyOperand, PyArgument, GraphRecordValue]
    ) -> PyOperand: ...
    def drop_duplicates(self) -> PyOperand: ...
    def is_duplicated(self) -> PyOperand: ...
    def unique(self) -> PyOperand: ...
    def take(self, elements: int) -> PyOperand: ...
    def is_bool(self) -> PyOperand: ...
    def is_datetime(self) -> PyOperand: ...
    def is_duration(self) -> PyOperand: ...
    def is_float(self) -> PyOperand: ...
    def is_null(self) -> PyOperand: ...
    def is_int(self) -> PyOperand: ...
    def is_string(self) -> PyOperand: ...
    def abs(self) -> PyOperand: ...
    def neg(self) -> PyOperand: ...
    def sign(self) -> PyOperand: ...
    def ceil(self) -> PyOperand: ...
    def cbrt(self) -> PyOperand: ...
    def exp(self) -> PyOperand: ...
    def floor(self) -> PyOperand: ...
    def log(self) -> PyOperand: ...
    def round(self) -> PyOperand: ...
    def sqrt(self) -> PyOperand: ...
    def trim(self) -> PyOperand: ...
    def trim_start(self) -> PyOperand: ...
    def trim_end(self) -> PyOperand: ...
    def lowercase(self) -> PyOperand: ...
    def uppercase(self) -> PyOperand: ...
    def reverse(self) -> PyOperand: ...
    def length(self) -> PyOperand: ...
    def slice(self, start: int, end: int) -> PyOperand: ...
    def starts_with(
        self, prefix: Union[PyOperand, PyArgument, GraphRecordValue]
    ) -> PyOperand: ...
    def ends_with(
        self, suffix: Union[PyOperand, PyArgument, GraphRecordValue]
    ) -> PyOperand: ...
    def contains(
        self, part: Union[PyOperand, PyArgument, GraphRecordValue]
    ) -> PyOperand: ...
    def matches(
        self, pattern: Union[PyOperand, PyArgument, GraphRecordValue]
    ) -> PyOperand: ...
    def strip_prefix(
        self, prefix: Union[PyOperand, PyArgument, GraphRecordValue]
    ) -> PyOperand: ...
    def strip_suffix(
        self, suffix: Union[PyOperand, PyArgument, GraphRecordValue]
    ) -> PyOperand: ...
    def replace(
        self,
        old: Union[PyOperand, PyArgument, GraphRecordValue],
        new: Union[PyOperand, PyArgument, GraphRecordValue],
    ) -> PyOperand: ...
    def replace_all(
        self,
        old: Union[PyOperand, PyArgument, GraphRecordValue],
        new: Union[PyOperand, PyArgument, GraphRecordValue],
    ) -> PyOperand: ...
    def pad_start(
        self,
        width: Union[PyOperand, PyArgument, int],
        character: Union[PyOperand, PyArgument, GraphRecordValue],
    ) -> PyOperand: ...
    def pad_end(
        self,
        width: Union[PyOperand, PyArgument, int],
        character: Union[PyOperand, PyArgument, GraphRecordValue],
    ) -> PyOperand: ...
    def split(
        self, delimiter: Union[PyOperand, PyArgument, GraphRecordValue]
    ) -> PyOperand: ...
    def attribute(self, attribute: Union[str, int]) -> PyOperand: ...
    def attributes(self) -> PyOperand: ...
    def resolve(self) -> PyOperand: ...
    def select(self) -> PyOperand: ...
    def parent_index(self) -> PyOperand: ...
    def child_index(self) -> PyOperand: ...
    def has_attribute(self, attribute: Union[str, int]) -> PyOperand: ...
    def in_group(self, group: Union[str, int]) -> PyOperand: ...
    def add(
        self, value: Union[PyOperand, PyArgument, GraphRecordValue]
    ) -> PyOperand: ...
    def subtract(
        self, value: Union[PyOperand, PyArgument, GraphRecordValue]
    ) -> PyOperand: ...
    def multiply(
        self, value: Union[PyOperand, PyArgument, GraphRecordValue]
    ) -> PyOperand: ...
    def power(
        self, value: Union[PyOperand, PyArgument, GraphRecordValue]
    ) -> PyOperand: ...
    def modulo(
        self, value: Union[PyOperand, PyArgument, GraphRecordValue]
    ) -> PyOperand: ...
    def divide(
        self, value: Union[PyOperand, PyArgument, GraphRecordValue]
    ) -> PyOperand: ...
    def clip(
        self,
        lower: Union[PyOperand, PyArgument, GraphRecordValue],
        upper: Union[PyOperand, PyArgument, GraphRecordValue],
    ) -> PyOperand: ...
    def cast(self, target: PyCastTarget) -> PyOperand: ...
    def equal_to(
        self, value: Union[PyOperand, PyArgument, GraphRecordValue, PyFailureKind]
    ) -> PyOperand: ...
    def not_equal_to(
        self, value: Union[PyOperand, PyArgument, GraphRecordValue, PyFailureKind]
    ) -> PyOperand: ...
    def greater_than(
        self, value: Union[PyOperand, PyArgument, GraphRecordValue]
    ) -> PyOperand: ...
    def greater_than_or_equal_to(
        self, value: Union[PyOperand, PyArgument, GraphRecordValue]
    ) -> PyOperand: ...
    def less_than(
        self, value: Union[PyOperand, PyArgument, GraphRecordValue]
    ) -> PyOperand: ...
    def less_than_or_equal_to(
        self, value: Union[PyOperand, PyArgument, GraphRecordValue]
    ) -> PyOperand: ...
    def is_in(
        self, values: Union[Sequence[GraphRecordValue], PyOperand, PyArgument]
    ) -> PyOperand: ...
    def index(self) -> PyOperand: ...
    def discard_index(self) -> PyOperand: ...
    def discard_value(self) -> PyOperand: ...
    def enumerate(self) -> PyOperand: ...
    def errors(self) -> PyOperand: ...
    def on_error_raise(self) -> PyOperand: ...
    def on_error_drop(self) -> PyOperand: ...
    def on_error_replace(
        self, replacement: Union[PyOperand, PyArgument, GraphRecordValue, PyFailureKind]
    ) -> PyOperand: ...
    def raise_when(
        self, condition: Union[PyOperand, PyArgument, bool]
    ) -> PyOperand: ...
    def kind(self) -> PyOperand: ...
    def name(self) -> PyOperand: ...
    def count(self) -> PyOperand: ...
    def sum(self) -> PyOperand: ...
    def mean(self) -> PyOperand: ...
    def std(self) -> PyOperand: ...
    def var(self) -> PyOperand: ...
    def all(self) -> PyOperand: ...
    def any(self) -> PyOperand: ...
    def max(self) -> PyOperand: ...
    def min(self) -> PyOperand: ...
    def median(self) -> PyOperand: ...
    def mode(self) -> PyOperand: ...
    def product(self) -> PyOperand: ...
    def n_unique(self) -> PyOperand: ...
    def random(self) -> PyOperand: ...
    def edges(self, direction: PyEdgeDirection) -> PyOperand: ...
    def neighbors(self, direction: PyEdgeDirection) -> PyOperand: ...
    def via_edges(self, direction: PyEdgeDirection) -> PyOperand: ...
    def via_neighbors(self, direction: PyEdgeDirection) -> PyOperand: ...
    def nodes(self) -> PyOperand: ...
    def via_nodes(self) -> PyOperand: ...
    def source_node(self) -> PyOperand: ...
    def target_node(self) -> PyOperand: ...
    def via_source_node(self) -> PyOperand: ...
    def via_target_node(self) -> PyOperand: ...
    def group_by(
        self, key: Union[PyOperand, PyArgument, GraphRecordValue]
    ) -> PyOperand: ...
    def having(self, predicate: Union[PyOperand, PyArgument, bool]) -> PyOperand: ...
    def keys(self) -> PyOperand: ...
    def ungroup(self) -> PyOperand: ...
    def ungroup_keyed(self) -> PyOperand: ...
    def broadcast(self) -> PyOperand: ...
    def broadcast_via(self, population: PyOperand) -> PyOperand: ...
    def bucket_errors(self) -> PyOperand: ...
    def key_errors(self) -> PyOperand: ...
    def on_bucket_error_drop(self) -> PyOperand: ...
    def on_bucket_error_raise(self) -> PyOperand: ...
    def on_key_error_drop(self) -> PyOperand: ...
    def on_key_error_raise(self) -> PyOperand: ...
    def transition(self, target: PyValueTarget) -> PyOperand: ...
    def expand_to(
        self, values: Union[PyOperand, PyArgument, GraphRecordValue]
    ) -> PyOperand: ...
