from typing import (
    Any,
    Iterable,
    Iterator,
    List,
    Optional,
    Tuple,
    TypeAlias,
    Union,
)

from typing_extensions import Self

from graphrecords._graphrecords.graphrecord import PyEdgeDirection, PyEdgeIndex
from graphrecords.types import AttributeName, GroupIndex, Value

Argument: TypeAlias = Union[
    Value,
    PyExpression,
    PySeries,
    PyArgument,
    PyFailureKind,
    PyEdgeIndex,
    PyEdgeEndpointRole,
]
MaskArgument: TypeAlias = Union[
    bool,
    PyExpression,
    PySeries,
    PyArgument,
]
PopulationArgument: TypeAlias = Union[
    PyExpression,
    PySeries,
]
SetArgument: TypeAlias = Union[
    Iterable[Union[Value, PyEdgeIndex, PyFailureKind, PyEdgeEndpointRole]],
    PyExpression,
    PySeries,
    PyArgument,
]

class PyEdgeEndpointRole:
    Source: PyEdgeEndpointRole
    Target: PyEdgeEndpointRole

    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class PyCastTarget:
    Bool: PyCastTarget
    DateTime: PyCastTarget
    Duration: PyCastTarget
    Float: PyCastTarget
    Int: PyCastTarget
    String: PyCastTarget

    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class PyValueTarget:
    Value: PyValueTarget
    ValueIndex: PyValueTarget
    AttributeName: PyValueTarget
    AttributeNameIndex: PyValueTarget
    NodeIndex: PyValueTarget
    GroupIndex: PyValueTarget
    PositionalIndex: PyValueTarget
    BoolIndex: PyValueTarget
    Mask: PyValueTarget
    FailureKind: PyValueTarget
    FailureKindIndex: PyValueTarget

    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class PyFailureKind:
    @property
    def name(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class PyArgument: ...

class PyResultView:
    def __iter__(self) -> PyResultView: ...
    def __next__(self) -> object: ...

class PyGroupedResult:
    @property
    def key_failures(self) -> List[Tuple[Any, Any]]: ...
    def __len__(self) -> int: ...
    def __contains__(self, key: object) -> bool: ...
    def __getitem__(self, key: object) -> object: ...
    def __iter__(self) -> Iterator[Any]: ...
    def keys(self) -> List[Any]: ...

class _Surface:
    def on_missing_drop(self) -> PyArgument: ...
    def on_missing_replace(self, replacement: Argument) -> PyArgument: ...
    def filter(self, mask: MaskArgument) -> Self: ...
    def and_(self, other: MaskArgument) -> Self: ...
    def or_(self, other: MaskArgument) -> Self: ...
    def xor(self, other: MaskArgument) -> Self: ...
    def not_(self) -> Self: ...
    def first(self) -> Self: ...
    def last(self) -> Self: ...
    def reverse_order(self) -> Self: ...
    def shuffle(self) -> Self: ...
    def unorder(self) -> Self: ...
    def sort(self) -> Self: ...
    def sort_by(self, key: Argument) -> Self: ...
    def drop_duplicates(self) -> Self: ...
    def is_duplicated(self) -> Self: ...
    def unique(self) -> Self: ...
    def take(self, elements: int) -> Self: ...
    def is_bool(self) -> Self: ...
    def is_datetime(self) -> Self: ...
    def is_duration(self) -> Self: ...
    def is_float(self) -> Self: ...
    def is_null(self) -> Self: ...
    def is_int(self) -> Self: ...
    def is_string(self) -> Self: ...
    def abs(self) -> Self: ...
    def neg(self) -> Self: ...
    def sign(self) -> Self: ...
    def ceil(self) -> Self: ...
    def cbrt(self) -> Self: ...
    def exp(self) -> Self: ...
    def floor(self) -> Self: ...
    def log(self) -> Self: ...
    def round(self) -> Self: ...
    def sqrt(self) -> Self: ...
    def trim(self) -> Self: ...
    def trim_start(self) -> Self: ...
    def trim_end(self) -> Self: ...
    def lowercase(self) -> Self: ...
    def uppercase(self) -> Self: ...
    def reverse(self) -> Self: ...
    def length(self) -> Self: ...
    def slice(self, start: int, end: int) -> Self: ...
    def starts_with(self, argument: Argument) -> Self: ...
    def ends_with(self, argument: Argument) -> Self: ...
    def contains(self, argument: Argument) -> Self: ...
    def matches(self, pattern: Argument) -> Self: ...
    def strip_prefix(self, prefix: Argument) -> Self: ...
    def strip_suffix(self, suffix: Argument) -> Self: ...
    def replace(self, old: Argument, new: Argument) -> Self: ...
    def replace_all(self, old: Argument, new: Argument) -> Self: ...
    def pad_start(self, width: int, character: Argument) -> Self: ...
    def pad_end(self, width: int, character: Argument) -> Self: ...
    def split(self, delimiter: Argument) -> Self: ...
    def attribute(self, attribute: AttributeName) -> Self: ...
    def attributes(self) -> Self: ...
    def resolve(self) -> Self: ...
    def select(self) -> Self: ...
    def parent_index(self) -> Self: ...
    def child_index(self) -> Self: ...
    def has_attribute(self, attribute: AttributeName) -> Self: ...
    def in_group(self, group_index: GroupIndex) -> Self: ...
    def add(self, argument: Argument) -> Self: ...
    def subtract(self, argument: Argument) -> Self: ...
    def multiply(self, argument: Argument) -> Self: ...
    def power(self, argument: Argument) -> Self: ...
    def modulo(self, argument: Argument) -> Self: ...
    def divide(self, argument: Argument) -> Self: ...
    def clip(self, lower: Argument, upper: Argument) -> Self: ...
    def cast(self, target: PyCastTarget) -> Self: ...
    def equal_to(self, argument: Argument) -> Self: ...
    def not_equal_to(self, argument: Argument) -> Self: ...
    def greater_than(self, argument: Argument) -> Self: ...
    def greater_than_or_equal_to(self, argument: Argument) -> Self: ...
    def less_than(self, argument: Argument) -> Self: ...
    def less_than_or_equal_to(self, argument: Argument) -> Self: ...
    def is_in(self, argument: SetArgument) -> Self: ...
    def index(self) -> Self: ...
    def discard_index(self) -> Self: ...
    def discard_value(self) -> Self: ...
    def enumerate(self) -> Self: ...
    def errors(self) -> Self: ...
    def on_error_raise(self) -> Self: ...
    def on_error_drop(self) -> Self: ...
    def on_error_replace(self, replacement: Argument) -> Self: ...
    def on_error_raise_when(self, condition: MaskArgument) -> Self: ...
    def kind(self) -> Self: ...
    def name(self) -> Self: ...
    def count(self) -> Self: ...
    def sum(self) -> Self: ...
    def mean(self) -> Self: ...
    def std(self) -> Self: ...
    def var(self) -> Self: ...
    def all(self) -> Self: ...
    def any(self) -> Self: ...
    def max(self) -> Self: ...
    def min(self) -> Self: ...
    def median(self) -> Self: ...
    def mode(self) -> Self: ...
    def product(self) -> Self: ...
    def n_unique(self) -> Self: ...
    def random(self) -> Self: ...
    def edges(self, direction: Optional[PyEdgeDirection] = None) -> Self: ...
    def neighbors(self, direction: PyEdgeDirection = ...) -> Self: ...
    def via_edges(self, direction: Optional[PyEdgeDirection] = None) -> Self: ...
    def via_neighbors(self, direction: PyEdgeDirection = ...) -> Self: ...
    def nodes(self) -> Self: ...
    def via_nodes(self) -> Self: ...
    def groups(self) -> Self: ...
    def via_groups(self) -> Self: ...
    def node_count(self) -> Self: ...
    def edge_count(self) -> Self: ...
    def source_node(self) -> Self: ...
    def target_node(self) -> Self: ...
    def via_source_node(self) -> Self: ...
    def via_target_node(self) -> Self: ...
    def group_by(self, key: Argument) -> Self: ...
    def having(self, predicate: MaskArgument) -> Self: ...
    def keys(self) -> Self: ...
    def ungroup(self) -> Self: ...
    def ungroup_keyed(self) -> Self: ...
    def broadcast(self) -> Self: ...
    def broadcast_via(self, via: PopulationArgument) -> Self: ...
    def bucket_errors(self) -> Self: ...
    def key_errors(self) -> Self: ...
    def on_bucket_error_drop(self) -> Self: ...
    def on_bucket_error_raise(self) -> Self: ...
    def on_key_error_drop(self) -> Self: ...
    def on_key_error_raise(self) -> Self: ...
    def transition(self, target: PyValueTarget) -> Self: ...
    def inherit(self, values: Argument) -> Self: ...

class PyExpression(_Surface):
    def cache(self) -> Self: ...
    def explain(self) -> str: ...

class PySeries(_Surface):
    def cache(self) -> Self: ...
    def evaluate(self) -> object: ...
    def explain(self) -> str: ...
    def explain_unoptimized(self) -> str: ...

def nodes() -> PyExpression: ...
def edges() -> PyExpression: ...
def groups() -> PyExpression: ...

class QueryError(Exception): ...
class ArgumentMissingError(QueryError): ...
class DivisionByZeroError(QueryError): ...
class DuplicateExpandedChildIndexError(QueryError): ...
class DuplicateIndexError(QueryError): ...
class EmptySplitDelimiterError(QueryError): ...
class EvaluationCacheGraphRecordMismatchError(QueryError): ...
class ExternalError(QueryError): ...
class GraphRecordError(QueryError): ...
class IncomparableIndicesError(QueryError): ...
class IncomparableValuesAtError(QueryError): ...
class IncomparableValuesError(QueryError): ...
class IntegerOverflowError(QueryError): ...
class InvalidCastError(QueryError): ...
class InvalidClipBoundsError(QueryError): ...
class InvalidMedianValueError(QueryError): ...
class InvalidPaddingCharacterError(QueryError): ...
class InvalidPartitionBucketArityError(QueryError): ...
class InvalidRegexPatternError(QueryError): ...
class InvalidStandardDeviationValueError(QueryError): ...
class InvalidStringSliceError(QueryError): ...
class InvalidTransitionError(QueryError): ...
class InvalidVarianceValueError(QueryError): ...
class MissingAttributeError(QueryError): ...
class MissingGroupAggregateError(QueryError): ...
class MissingGroupBucketError(QueryError): ...
class MissingTraversedAttributeError(QueryError): ...
class ModuloByZeroError(QueryError): ...
class NegativeSquareRootError(QueryError): ...
class NoChildIndexError(QueryError): ...
class NonIntegerValueError(QueryError): ...
class NonNumericValueError(QueryError): ...
class NonPositiveLogarithmError(QueryError): ...
class NonStringValueError(QueryError): ...
class RaisedFailuresError(QueryError): ...
class StringLengthOverflowError(QueryError): ...
class StringPaddingOverflowError(QueryError): ...
class UncoveredIndicesError(QueryError): ...
class UnresolvedBucketFailuresError(QueryError): ...
class UnresolvedGroupKeyFailuresError(QueryError): ...
class UnresolvedIndexError(QueryError): ...
class UnsupportedValueRoleError(QueryError): ...
class ResultConsumedError(RuntimeError): ...
