name: Format Pull Request

on:
  pull_request:

jobs:
  format:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt

      - name: Install uv
        uses: astral-sh/setup-uv@d4b2f3b6ecc6e67c4457f6d3e41ec42d3d0fcb86 # v5
        with:
          enable-cache: true
          cache-dependency-glob: pyproject.toml
          python-version: "3.10"

      - name: Install dependencies
        run: |
          uv sync --no-install-project --group dev

      - name: Format with ruff
        run: uv run --no-sync ruff format --check

      - name: Format with rustfmt
        run: cargo +nightly fmt -- --check
